version: '2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.0.2
    ports:
      - 9200:9200
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1  

  kibana:
    image: docker.elastic.co/kibana/kibana:5.0.2
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_URL: http://es:9200
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5601
      
